# Generated by Django 5.2.14 on 2026-07-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('csv_file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('holiday_flag', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('fuel_price', models.FloatField()),
                ('cpi', models.FloatField()),
                ('unemployment', models.FloatField()),
                ('year', models.IntegerField(default=2025)),
                ('month', models.IntegerField(default=1)),
                ('week', models.IntegerField(default=1)),
                ('quarter', models.IntegerField(default=1)),
                ('predicted_sales', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sales_quantity', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_date', models.DateField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
