# Generated by Django 5.2.14 on 2026-07-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='region',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sales_date',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sales_quantity',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='cpi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='fuel_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='holiday_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='quarter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='store',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='unemployment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='weekly_sales',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
